language: rust

env:
  global:
    - secure: NH8PgBMd7QlQAnYn+yLniTDRfsJ9Y+yhrpWPZI+RLvm1e2j+v66NV2ysuG7DFIQM/vzJE8s6+gmqTkC3hq/zPwVF6FpOLWWUM0Jtl8W5L/NulUcjLaFForDzcPOaoMprb17L1ZQdvVXYyg4TiCJH9KsuHC58ETH6y/0NkfuPqnI=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
